# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: elm
    directory: /
    schedule:
      interval: "daily"
    assignees:
      - emilgoldsmith
    reviewers:
      - emilgoldsmith

  - package-ecosystem: elm
    directory: /review/
    schedule:
      interval: "daily"
    assignees:
      - emilgoldsmith
    reviewers:
      - emilgoldsmith

  - package-ecosystem: npm
    directory: /end-to-end-tests/
    schedule:
      interval: "daily"
    assignees:
      - emilgoldsmith
    reviewers:
      - emilgoldsmith
    versioning-strategy: increase
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "eslint-*"
      - dependency-name: "@typescript-eslint/*"
      - dependency-name: prettier
      - dependency-name: "@sinonjs/fake-timers"
      - dependency-name: "@percy/cli"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "daily"
    assignees:
      - emilgoldsmith
    reviewers:
      - emilgoldsmith
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "daily"
    assignees:
      - emilgoldsmith
    reviewers:
      - emilgoldsmith
