module VerifyExamples.Models.Cube.EdgeLocations0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Models.Cube exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#edgeLocations: \n\n    List.length edgeLocations\n    --> 12" <|
        \() ->
            Expect.equal
                (
                List.length edgeLocations
                )
                (
                12
                )