module VerifyExamples.Algorithm.AllTurnDirections0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Algorithm exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#allTurnDirections: \n\n    List.length allTurnDirections\n    --> 2" <|
        \() ->
            Expect.equal
                (
                List.length allTurnDirections
                )
                (
                2
                )