module VerifyExamples.Algorithm.AllTurns0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Algorithm exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#allTurns: \n\n    List.length allTurns\n    --> List.length allTurnables * List.length allTurnLengths * List.length allTurnDirections" <|
        \() ->
            Expect.equal
                (
                List.length allTurns
                )
                (
                List.length allTurnables * List.length allTurnLengths * List.length allTurnDirections
                )