module VerifyExamples.Algorithm.AllTurnables0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Algorithm exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#allTurnables: \n\n    List.length allTurnables\n    --> 12" <|
        \() ->
            Expect.equal
                (
                List.length allTurnables
                )
                (
                12
                )