module VerifyExamples.AlgorithmRepository.AllPlls0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AlgorithmRepository exposing (..)
import List.Nonempty







spec0 : Test.Test
spec0 =
    Test.test "#allPlls: \n\n    List.Nonempty.length allPlls\n    --> 18" <|
        \() ->
            Expect.equal
                (
                List.Nonempty.length allPlls
                )
                (
                18
                )