module VerifyExamples.AlgorithmRepository.PllList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AlgorithmRepository exposing (..)
import Utils.NonEmptyList as NonEmptyList







spec0 : Test.Test
spec0 =
    Test.test "#pllList: \n\n    List.length <| NonEmptyList.toList pllList\n    --> 14" <|
        \() ->
            Expect.equal
                (
                List.length <| NonEmptyList.toList pllList
                )
                (
                14
                )