module VerifyExamples.AlgorithmRepository.ReferencePlls0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AlgorithmRepository exposing (..)
import Models.Algorithm







spec0 : Test.Test
spec0 =
    Test.test "#referencePlls: \n\n    Models.Algorithm.fromString \"R2 F R U R U' R' F' R U2 R' U2 R\"\n    --> Ok referencePlls.rb" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "R2 F R U R U' R' F' R U2 R' U2 R"
                )
                (
                Ok referencePlls.rb
                )