module VerifyExamples.AlgorithmRepository.ReferencePlls1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AlgorithmRepository exposing (..)
import Models.Algorithm







spec1 : Test.Test
spec1 =
    Test.test "#referencePlls: \n\n    Models.Algorithm.fromString \"R B' R F2 R' B R F2 R2\"\n    --> Ok referencePlls.ab" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "R B' R F2 R' B R F2 R2"
                )
                (
                Ok referencePlls.ab
                )