module VerifyExamples.AlgorithmRepository.ReferencePlls2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AlgorithmRepository exposing (..)
import Models.Algorithm







spec2 : Test.Test
spec2 =
    Test.test "#referencePlls: \n\n    Models.Algorithm.fromString \"B2 (L U L') B2 (R D' R D) R2\"\n    --> Ok referencePlls.jb" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "B2 (L U L') B2 (R D' R D) R2"
                )
                (
                Ok referencePlls.jb
                )