module VerifyExamples.AlgorithmRepository.ReferencePlls1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AlgorithmRepository exposing (..)
import Models.Algorithm







spec1 : Test.Test
spec1 =
    Test.test "#referencePlls: \n\n    Models.Algorithm.fromString \"D R' D2 F' D L D' F D2 R D' F' L' F\"\n    --> Ok referencePlls.e" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "D R' D2 F' D L D' F D2 R D' F' L' F"
                )
                (
                Ok referencePlls.e
                )