module VerifyExamples.AlgorithmRepository.ReferencePlls2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AlgorithmRepository exposing (..)
import Models.Algorithm







spec2 : Test.Test
spec2 =
    Test.test "#referencePlls: \n\n    Models.Algorithm.fromString \"R' U' R B2 D (L' U L U' L) D' B2\"\n    --> Ok referencePlls.gb" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "R' U' R B2 D (L' U L U' L) D' B2"
                )
                (
                Ok referencePlls.gb
                )