module VerifyExamples.AlgorithmRepository.ReferencePlls3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AlgorithmRepository exposing (..)
import Models.Algorithm







spec3 : Test.Test
spec3 =
    Test.test "#referencePlls: \n\n    Models.Algorithm.fromString \"L U' R U2 L' U R' L U' R U2 L' U R'\"\n    --> Ok referencePlls.na" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "L U' R U2 L' U R' L U' R U2 L' U R'"
                )
                (
                Ok referencePlls.na
                )