module VerifyExamples.AlgorithmRepository.ReferencePlls0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AlgorithmRepository exposing (..)
import Models.Algorithm







spec0 : Test.Test
spec0 =
    Test.test "#referencePlls: \n\n    Models.Algorithm.fromString \"R' U L' U2 R U' L R' U L' U2 R U' L\"\n    --> Ok referencePlls.nb" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "R' U L' U2 R U' L R' U L' U2 R U' L"
                )
                (
                Ok referencePlls.nb
                )