module VerifyExamples.PLL.ReferenceAlgs13 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Models.Algorithm







spec13 : Test.Test
spec13 =
    Test.test "#referenceAlgs: \n\n    Models.Algorithm.fromString \"L F R' F' L' F' D2 B' L' B D2 F' R F2\"\n    --> Ok referenceAlgs.f" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "L F R' F' L' F' D2 B' L' B D2 F' R F2"
                )
                (
                Ok referenceAlgs.f
                )