module VerifyExamples.PLL.ReferenceAlgs19 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Models.Algorithm







spec19 : Test.Test
spec19 =
    Test.test "#referenceAlgs: \n\n    Models.Algorithm.fromString \"F2 U' (L R') F2 (L' R) U' F2\"\n    --> Ok referenceAlgs.ua" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "F2 U' (L R') F2 (L' R) U' F2"
                )
                (
                Ok referenceAlgs.ua
                )