module VerifyExamples.PLL.ReferenceAlgs9 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Models.Algorithm







spec9 : Test.Test
spec9 =
    Test.test "#referenceAlgs: \n\n    Models.Algorithm.fromString \"R U R' F2 D' (L U' L' U L') D F2\"\n    --> Ok referenceAlgs.gd" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "R U R' F2 D' (L U' L' U L') D F2"
                )
                (
                Ok referenceAlgs.gd
                )