module VerifyExamples.PLL.ReferenceAlgs17 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Algorithm







spec17 : Test.Test
spec17 =
    Test.test "#referenceAlgs: \n\n    Algorithm.fromString \"R B' R' B F R' F B' R' B R F2\"\n    --> Ok referenceAlgs.z" <|
        \() ->
            Expect.equal
                (
                Algorithm.fromString "R B' R' B F R' F B' R' B R F2"
                )
                (
                Ok referenceAlgs.z
                )