module VerifyExamples.PLL.ReferenceAlgs16 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Models.Algorithm







spec16 : Test.Test
spec16 =
    Test.test "#referenceAlgs: \n\n    Models.Algorithm.fromString \"R' F R' B2 R F' R' B2 R2\"\n    --> Ok referenceAlgs.aa" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "R' F R' B2 R F' R' B2 R2"
                )
                (
                Ok referenceAlgs.aa
                )