module VerifyExamples.PLL.ReferenceAlgs5 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Algorithm







spec5 : Test.Test
spec5 =
    Test.test "#referenceAlgs: \n\n    Algorithm.fromString \"R' U L' U2 R U' L R' U L' U2 R U' L\"\n    --> Ok referenceAlgs.nb" <|
        \() ->
            Expect.equal
                (
                Algorithm.fromString "R' U L' U2 R U' L R' U L' U2 R U' L"
                )
                (
                Ok referenceAlgs.nb
                )