module VerifyExamples.PLL.ReferenceAlgs2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Algorithm







spec2 : Test.Test
spec2 =
    Test.test "#referenceAlgs: \n\n    Algorithm.fromString \"F2 D R2 U' R2 F2 D' L2 U L2\"\n    --> Ok referenceAlgs.t" <|
        \() ->
            Expect.equal
                (
                Algorithm.fromString "F2 D R2 U' R2 F2 D' L2 U L2"
                )
                (
                Ok referenceAlgs.t
                )