module VerifyExamples.PLL.ReferenceAlgs15 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Algorithm







spec15 : Test.Test
spec15 =
    Test.test "#referenceAlgs: \n\n    Algorithm.fromString \"R B' R F2 R' B R F2 R2\"\n    --> Ok referenceAlgs.ab" <|
        \() ->
            Expect.equal
                (
                Algorithm.fromString "R B' R F2 R' B R F2 R2"
                )
                (
                Ok referenceAlgs.ab
                )