module VerifyExamples.PLL.ReferenceAlgs14 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Models.Algorithm







spec14 : Test.Test
spec14 =
    Test.test "#referenceAlgs: \n\n    Models.Algorithm.fromString \"D R' D2 F' D L D' F D2 R D' F' L' F\"\n    --> Ok referenceAlgs.e" <|
        \() ->
            Expect.equal
                (
                Models.Algorithm.fromString "D R' D2 F' D L D' F D2 R D' F' L' F"
                )
                (
                Ok referenceAlgs.e
                )