module VerifyExamples.PLL.ReferenceAlgs8 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Algorithm







spec8 : Test.Test
spec8 =
    Test.test "#referenceAlgs: \n\n    Algorithm.fromString \"B2 R' U' R B2 L' D L' D' L2\"\n    --> Ok referenceAlgs.ja" <|
        \() ->
            Expect.equal
                (
                Algorithm.fromString "B2 R' U' R B2 L' D L' D' L2"
                )
                (
                Ok referenceAlgs.ja
                )