module VerifyExamples.Cube.Faces0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Cube exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#faces: \n\n    List.length faces\n    --> 6" <|
        \() ->
            Expect.equal
                (
                List.length faces
                )
                (
                6
                )