##### This workflow uses pull_request target which allows forked and Dependabot
##### PRs access to our secrets. Be very careful with what you do here, and don't
##### ever check out and run the code unless you're absolutely sure it's bullet proof
name: Build And Push Docker Containers
on:
  push:
    branches: main
  pull_request_target: {}

jobs:
  get-ref-and-sha:
    name: Get Ref And SHA
    runs-on: ubuntu-20.04
    outputs:
      sha: ${{ steps.output.outputs.sha }}
      ref: ${{ steps.output.outputs.ref }}
    steps:
      - name: Output the ref and sha depending on event type
        id: output
        env:
          EVENT_NAME: ${{ github.event_name }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: >
          echo "GITHUB_CONTEXT";
          (
            [[ "$EVENT_NAME" == 'push' ]] &&
            (
              echo "::set-output name=sha::${{ github.sha }}" &&
              echo "::set-output name=ref::${{ github.ref }}"
            )
          ) ||
          (
            [[ "$EVENT_NAME" == 'pull_request_target' ]] &&
            (
              echo "::set-output name=sha::${{ github.event.pull_request.head.sha }}" &&
              echo "::set-output name=ref::${{ github.event.pull_request.head.ref }}"
            )
          ) ||
          (
            echo "ERROR: Unexpected event name $EVENT_NAME" &&
            exit 1
          )

  main:
    name: main
    runs-on: ubuntu-20.04
    needs: get-ref-and-sha
    env:
      repository: sctrainer/main
      ci-container-tag: ci-container-v1
      ci-chrome-tag: ci-chrome-v1
      production-tag: production-${{ needs.get-ref-and-sha.outputs.sha }}
    steps:
      # The only reason we checkout this unsafe code is because we are
      # certain that docker builds run in a fully secure contained environment
      # where it won't have access to our secrets. Don't do anything else with
      # this code! Especially don't allow it to execute in any way!
      - name: Checkout possibly unsafe code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.get-ref-and-sha.outputs.ref }}

      # Being extra sure that people can't tamper with anything related to these secrets
      - name: Ensure Dockerfile Wasn't Changed If Untrusted Source
        if: ${{ github.event_name == 'pull_request_target' && github.event.pull_quest.author_association != 'OWNER' }}
        run: git fetch origin main && git diff --exit-code origin/main Dockerfile

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if CI Container image already up to date
        id: ci-container-up-to-date
        run: curl --silent -f -lSL https://index.docker.io/v1/repositories/${{ env.repository }}/tags/${{ env.ci-container-tag }}
        continue-on-error: true

      - name: Build and Push CI Container image
        uses: docker/build-push-action@v2
        if: ${{ needs.ci-container-up-to-date.outcome == 'failure' }}
        with:
          push: true
          target: ci
          tags: ${{ env.repository }}:${{ env.ci-container-tag }}

      - name: Check if CI Chrome image already up to date
        id: ci-chrome-up-to-date
        run: curl --silent -f -lSL https://index.docker.io/v1/repositories/${{ env.repository }}/tags/${{ env.ci-chrome-tag }}
        continue-on-error: true

      - name: Build and Push CI Chrome image
        uses: docker/build-push-action@v2
        if: ${{ needs.ci-chrome-up-to-date.outcome == 'failure' }}
        with:
          push: true
          target: ci-chrome
          tags: ${{ env.repository }}:${{ env.ci-chrome-tag }}

      - name: Build and Push Production image
        uses: docker/build-push-action@v2
        with:
          push: true
          target: production
          tags: ${{ env.repository }}:${{ env.production-tag }}
