on:
  check_suite:
    types: [completed]

jobs:
  test:
    steps:
      - run: echo "Success"
        if: ${{ github.event.check_suite.conclusion == "success" }}

      - run: echo "${{ github.event.check_suite.conclusion }}"
        if: ${{ github.event.check_suite.conclusion != "success" }}
