name: CI and CD
on: push

jobs:
  cypress-end-to-end-test:
    name: ${{ matrix.browser }} ${{ matrix.sizeRelevant.viewportConfig }} Cypress E2E Browser Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]
        # These are the macbook-13 and iphone-8 values from https://docs.cypress.io/api/commands/viewport#Arguments
        sizeRelevant:
          - viewportConfig: "viewportWidth=1280,viewportHeight=800"
            # We include the dynamic viewports just one place as it doesn't matter what initial
            # viewport size it is so no need to include it several times
            extraSpecs: [cypress/tests/uses-dynamic-viewports/*]
          - viewportConfig: "viewportWidth=375,viewportHeight=667"
            extraSpecs: []
        include:
          - browser: chrome
            os: ubuntu-latest
          - browser: firefox
            os: ubuntu-latest
          - browser: edge
            os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build -t sc-trainer:${{ github.sha }} --target production .

      - name: Start server
        run: docker run -e PORT=8080 -p 8080:8080 -d --name="sc-trainer-server" sc-trainer:${{ github.sha}}

      - name: Cypress Run
        uses: cypress-io/github-action@v2.9.11
        with:
          working-directory: end-to-end-tests
          browser: ${{ matrix.browser }}
          config: "${{ matrix.sizeRelevant.viewportConfig }},baseUrl=http://localhost:8080"
          wait-on: "http://localhost:8080"
          spec: |
            cypress/tests/*
            ${{ matrix.sizeRelevant.extraSpecs[0] }}
            ${{ matrix.sizeRelevant.extraSpecs[1] }}
            ${{ matrix.sizeRelevant.extraSpecs[2] }}
          # For debugging purposes log all the installed browsers and OS info
          build: npx cypress info
        env:
          # This allows the action to determine the unique run id
          # which is necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop server
        run: docker stop sc-trainer-server

  deploy:
    # We only deploy if it's the main branch and they were a success
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    # Important to keep this up to date, depending on all jobs
    needs: [cypress-end-to-end-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: python scripts/trigger-deploy.py
        env:
          SECRET: ${{ secrets.GOOGLE_CLOUD_DEPLOY_SECRET }}
          API_KEY: ${{ secrets.GOOGLE_CLOUD_DEPLOY_API_KEY }}
