name: Cypress End To End Tests
on: push

jobs:
  ui-chrome-desktop:
    name: UI Chrome Desktop Tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome89-ff86
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Cache docker layers for faster builds
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # As suggested by the action README
        continue-on-error: true

      - name: Build
        run: docker build -t sc-trainer:$GITHUB_SHA --target production .

      - name: Start server
        run: docker run -e PORT=8080 -d --name="sc-trainer-server" sc-trainer:$GITHUB_SHA

      - name: Cypress Run
        uses: cypress-io/github-action@v2.9.11
        with:
          working-directory: end-to-end-tests
          browser: chrome
          # These are the macbook-13 values from https://docs.cypress.io/api/commands/viewport#Arguments
          config: "viewportWidth=1280,viewportHeight=800"
          wait-on: "http://localhost:8080"
          spec: |
            cypress/tests/desktop-only/*
            cypress/tests/*
        env:
          # This allows the action to determine the unique run id
          # which is necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop server
        run: docker stop sc-trainer-server
