name: Continuous Deployment
on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait for CI to pass
        uses: emilgoldsmith/wait-for-workflows-to-succeed@v1.1
        with:
          wait-interval-seconds: 30
          wait-max-seconds: 180
          workflows: |
            ci.yml
            build-and-push-docker-containers.yml
          repo-token: ${{ github.token }}

      - name: Deploy newest version
        run: python scripts/trigger-deploy.py
        env:
          SECRET: ${{ secrets.GOOGLE_CLOUD_DEPLOY_SECRET }}
          API_KEY: ${{ secrets.GOOGLE_CLOUD_DEPLOY_API_KEY }}
