on:
  check_suite:
    types: [completed]

jobs:
  deploy_main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying!"
      - run: echo "${{ github.event.head_branch }}"
      - run: echo "${{ github.conclusion }}"
      - run: echo "${{ github.status }}"
